- name: wipe config on all switches
  hosts: all

  tasks:
  - name: wipe config on all switches
    nclu:
      atomic: true
      commands:
      - del all

- name: Configure spine01
  hosts: 172.16.255.101

  tasks: 
  - name: Configure spine switch
    nclu:
      atomic: true
      commands:
      - add bgp autonomous-system {{ spine_as }}
      - add bgp router-id {{ spine_rid }}
      - add bgp neighbor swp1 remote-as external
      - add bgp neighbor swp2 remote-as external

- name: Configure leaf01
  hosts: 172.16.255.111

  tasks: 
  - name: Configure leaf switches
    nclu: 
      atomic: true
      commands:
      - add interface {{ leaf01_swp }} ip address {{ leaf01_ip }}
      - add bgp autonomous-system {{ leaf01_as }}
      - add bgp router-id {{ leaf01_rid }}
      - add bgp neighbor swp1 remote-as external
      - add bgp network {{ leaf01_network }}

- name: Configure leaf02
  hosts: 172.16.255.112

  tasks: 
  - name: Configure leaf02
    nclu: 
      atomic: true
      commands:
      - add interface {{ leaf02_swp }} ip address {{ leaf02_ip }}
      - add bgp autonomous-system {{ leaf02_as }}
      - add bgp router-id {{ leaf02_rid }}
      - add bgp neighbor swp1 remote-as external
      - add bgp network {{ leaf02_network }}






