- name: wipe config on all switches
  hosts: all

#  tasks:
#  - name: wipe config on all switches
#    nclu:
#      atomic: true
#      commands:
#      - del all

- name: Configure spine switch
  hosts: 172.16.255.101

  tasks: 
  - name: configure spine switch
    nclu:
      atomic: true
      commands:
      - add bgp router-id {{ spine_rid }}
      - add bgp autonomous-system {{ spine_as }}
      - add bgp neighbor swp1 remote-as external
      - add bgp neighbor swp2 remote-as external

- name: configure leaf switches
  hosts: 172.16.255.111,172.16.255.112

  tasks: 
  - name: configure leaf switches
    nclu: 
      atomic: true
      commands:
      - add interface {{ item.swp }} ip address {{ item.ip }}
      - add bgp router-id {{ item.router-id }}
      - add bgp autonomous-system {{ item.as-number }}
      - add bgp neighbor swp1 remote-as external
    loop:
      - { router-id: {{ leaf01_rid }}, as-number: {{ leaf01_as }}, network: {{ leaf01_network }}, ip: {{ leaf01_ip }}, swp: {{ leaf01_swp }} }
      - { router-id: {{ leaf02_rid }}, as-number: {{ leaf02_as }}, network: {{ leaf02_network }}, ip: {{ leaf02_ip }}, swp: {{ leaf02_swp }} }






