- name: Configure CLAG on Leaf01 and Leaf02 Switches
  hosts: all

  tasks:
  - name: Set hostnames
    nclu:
        commit: true
        description: "Set hostnames"
        commands:
            - add hostname test-leaf01