- name: Configure 2 vlans and svi's
  hosts: all

  tasks:
  - name: reset switch config
    nclu:
      atomic: true
      commands:
        - del all

  - name: Configure bridge with vlan 10 and 20
    nclu:
        commit: false
        description: "configure vlan 10 and 20 on a vlan aware bridge"
        commands:
            - add bridge bridge vids {{ vlanid_1 }},{{ vlanid_2 }}

  - name: configure vlan {{ vlanid_1 }} svi
    nclu:
      commit: false
      description: "configure svi for 1st vlan"
      commands:
        - add vlan {{ vlanid_1 }} ip address {{ ip_1 }}
  
  - name: configure vlan {{ vlanid_2 }} svi
    nclu:
      commit: false
      description: "configure svi for 2nd vlan"
      commands:
        - add vlan {{ vlanid_2 }} ip address {{ ip_2 }}

  - name: configure access ports for vpc's
    nclu:
      commit: true
      commands:
        - add interface {{ swp_vlan_1 }} bridge access {{ vlanid_1 }}
        - add interface {{ swp_vlan_2 }} bridge access {{ vlanid_2 }}